export {default as NavBar} from './NavBar/NavBar';
export {default as LogIn}  from './Authentication/LogIn/LogIn';
export {default as CryptoCurrencies} from './CryptoCurrencies/CryptoCurrencies';
export {default as CryptoDetails} from './CryptoDetails/CryptoDetails';
export {default as Exchanges} from './Exchanges/Exchanges';
export {default as News} from './News/News';
export {default as HomePage} from './HomePage/HomePage';
export {default as Register} from './Authentication/Register/Register';
export {default as DashboardNavBar} from './Dashboard/DashboardNavBar/DashboardNavBar';
export {default as OwnedCurrencies} from './Dashboard/OwnedCurrencies/OwnedCurrencies'
export {default as TimeLine} from './Dashboard/TimeLine/TimeLine'